// <auto-generated />
namespace bmi.imis.MABanker.Careers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SeedDataAdded1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedDataAdded1));
        
        string IMigrationMetadata.Id
        {
            get { return "201409222102085_SeedDataAdded1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
